# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: cosmos-db-table-nodejs-quickstart
metadata:
  template: cosmos-db-table-nodejs-quickstart
services:
  javascript-web:
    project: ./src/js
    language: js
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
  typescript-web:
    project: ./src/ts
    language: ts
    host: containerapp
    docker:
      path: ./Dockerfile
      context: ./
pipeline:
  provider: github
hooks:
  postprovision:
    windows:
      shell: pwsh
      run: |
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=""$env:CONFIGURATION__AZURECOSMOSDB__ENDPOINT""
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=""$env:CONFIGURATION__AZURECOSMOSDB__TABLENAME""
        " > ./src/js/.env
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=""$env:CONFIGURATION__AZURECOSMOSDB__ENDPOINT""
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=""$env:CONFIGURATION__AZURECOSMOSDB__TABLENAME""
        " > ./src/ts/.env
      continueOnError: false
      interactive: true
    posix:
      shell: sh
      run: |
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=\"$CONFIGURATION__AZURECOSMOSDB__ENDPOINT\"
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=\"$CONFIGURATION__AZURECOSMOSDB__TABLENAME\"
        " > ./src/js/.env
        echo "
        CONFIGURATION__AZURECOSMOSDB__ENDPOINT=\"$CONFIGURATION__AZURECOSMOSDB__ENDPOINT\"
        CONFIGURATION__AZURECOSMOSDB__TABLENAME=\"$CONFIGURATION__AZURECOSMOSDB__TABLENAME\"
        " > ./src/ts/.env
      continueOnError: false
      interactive: true
